try out dry mode

diff --git a/.github/workflows/kestra-ee-publish-docker.yml b/.github/workflows/kestra-ee-publish-docker.yml
--- a/.github/workflows/kestra-ee-publish-docker.yml
+++ b/.github/workflows/kestra-ee-publish-docker.yml
@@ -29,6 +29,11 @@ on:
         required: false
         type: string
         default: "LATEST"
+      dry-run:
+        description: 'Dry run mode that will stop before publishing the image'
+        required: false
+        type: boolean
+        default: false
 
 env:
   PLUGIN_VERSION: ${{ inputs.plugin-version != '' && inputs.plugin-version || 'LATEST' }}
@@ -83,6 +88,12 @@ jobs:
       GCP_IMAGE_PATH: europe-west1-docker.pkg.dev/kestra-host/docker/kestra-ee
       GITHUB_IMAGE_PATH: ghcr.io/kestra-io/kestra-ee
     steps:
+      - name: test dry run ON
+        if: ${{ inputs.dry-run == true }}
+        run: echo 'dry run ON'
+      - name: test try run OFF
+        if: ${{ inputs.dry-run == false }}
+        run: echo 'dry run OFF'
       - name: Code Checkout
         uses: actions/checkout@v5
         with:
@@ -151,55 +162,55 @@ jobs:
           username: oauth2accesstoken
           password: ${{ steps.glogin.outputs.access_token }}
 
-      - name: Docker - Build and push
-        id: docker-build-push
-        uses: docker/build-push-action@v6
-        with:
-          context: kestra-ee/.
-          push: true
-          tags: |
-            ${{ env.GITHUB_IMAGE_PATH }}:${{ steps.vars.outputs.tag }}
-            ${{ env.GCP_IMAGE_PATH }}:${{ steps.vars.outputs.tag }}
-          platforms: linux/amd64,linux/arm64
-          network: host
-          build-args: |
-            KESTRA_PLUGINS=${{ steps.vars.outputs.plugins }}
-            APT_PACKAGES=${{ matrix.image.packages }}
-            PYTHON_LIBRARIES=${{ matrix.image.python-libraries }}
-
-
-      - name: Setup - Install regctl
-        if: startsWith(github.ref, 'refs/tags/v')
-        uses: regclient/actions/regctl-installer@main
-
-      - name: Retag to minor semver version
-        if: startsWith(github.ref, 'refs/tags/v') && steps.vars.outputs.minor_semver != ''
-        run: |
-          regctl image copy ${{ env.GCP_IMAGE_PATH }}:${{ steps.vars.outputs.tag }} ${{ env.GCP_IMAGE_PATH }}:${{ steps.vars.outputs.minor_semver }}${{ matrix.image.tag }}
-          regctl image copy ${{ env.GITHUB_IMAGE_PATH }}:${{ steps.vars.outputs.tag }} ${{ env.GITHUB_IMAGE_PATH }}:${{ steps.vars.outputs.minor_semver }}${{ matrix.image.tag }}
-
-      - name: Retag to latest
-        if: startsWith(github.ref, 'refs/tags/v') && (inputs.retag-latest == true || inputs.retag-latest == 'true')
-        run: |
-          echo "TODO remove this safety net after debugging inputs.retag-latest, its value: ${{ inputs.retag-latest }}"
-          TAG=${GITHUB_REF#refs/*/}
-          if [[ ! $TAG =~ ^v1\.0\.[0-9]+$ ]]; then
-            echo "error there is a bug, tag is probably not the expected one: $TAG"
-            exit 1
-          fi
-          
-          regctl image copy ${{ env.GCP_IMAGE_PATH }}:${{ steps.vars.outputs.tag }} ${{ env.GCP_IMAGE_PATH }}:latest${{ matrix.image.tag }}
-          regctl image copy ${{ env.GITHUB_IMAGE_PATH }}:${{ steps.vars.outputs.tag }} ${{ env.GITHUB_IMAGE_PATH }}:latest${{ matrix.image.tag }}
-
-      - name: Retag to LTS
-        if: startsWith(github.ref, 'refs/tags/v') && (inputs.retag-lts == true || inputs.retag-lts == 'true')
-        run: |
-          echo "TODO remove this safety net after debugging inputs.retag-lts, its value: ${{ inputs.retag-lts }}"
-          TAG=${GITHUB_REF#refs/*/}
-          if [[ ! $TAG =~ ^v1\.0\.[0-9]+$ ]]; then
-            echo "error there is a bug, tag is probably not the expected one: $TAG"
-            exit 1
-          fi
-          
-          regctl image copy ${{ env.GCP_IMAGE_PATH }}:${{ steps.vars.outputs.tag }} ${{ env.GCP_IMAGE_PATH }}:latest-lts${{ matrix.image.tag }}
-          regctl image copy ${{ env.GITHUB_IMAGE_PATH }}:${{ steps.vars.outputs.tag }} ${{ env.GITHUB_IMAGE_PATH }}:latest-lts${{ matrix.image.tag }}
+#      - name: Docker - Build and push
+#        id: docker-build-push
+#        uses: docker/build-push-action@v6
+#        with:
+#          context: kestra-ee/.
+#          push: ${{ !(inputs.dry-run == false || inputs.dry-run == 'false') }}
+#          tags: |
+#            ${{ env.GITHUB_IMAGE_PATH }}:${{ steps.vars.outputs.tag }}
+#            ${{ env.GCP_IMAGE_PATH }}:${{ steps.vars.outputs.tag }}
+#          platforms: linux/amd64,linux/arm64
+#          network: host
+#          build-args: |
+#            KESTRA_PLUGINS=${{ steps.vars.outputs.plugins }}
+#            APT_PACKAGES=${{ matrix.image.packages }}
+#            PYTHON_LIBRARIES=${{ matrix.image.python-libraries }}
+#
+#
+#      - name: Setup - Install regctl
+#        if: startsWith(github.ref, 'refs/tags/v')
+#        uses: regclient/actions/regctl-installer@main
+#
+#      - name: Retag to minor semver version
+#        if: startsWith(github.ref, 'refs/tags/v') && steps.vars.outputs.minor_semver != '' && (inputs.dry-run == false || inputs.dry-run == 'false')
+#        run: |
+#          regctl image copy ${{ env.GCP_IMAGE_PATH }}:${{ steps.vars.outputs.tag }} ${{ env.GCP_IMAGE_PATH }}:${{ steps.vars.outputs.minor_semver }}${{ matrix.image.tag }}
+#          regctl image copy ${{ env.GITHUB_IMAGE_PATH }}:${{ steps.vars.outputs.tag }} ${{ env.GITHUB_IMAGE_PATH }}:${{ steps.vars.outputs.minor_semver }}${{ matrix.image.tag }}
+#
+#      - name: Retag to latest
+#        if: startsWith(github.ref, 'refs/tags/v') && (inputs.dry-run == false || inputs.dry-run == 'false') && (inputs.retag-latest == true || inputs.retag-latest == 'true')
+#        run: |
+#          echo "TODO remove this safety net after debugging inputs.retag-latest, its value: ${{ inputs.retag-latest }}"
+#          TAG=${GITHUB_REF#refs/*/}
+#          if [[ ! $TAG =~ ^v1\.0\.[0-9]+$ ]]; then
+#            echo "error there is a bug, tag is probably not the expected one: $TAG"
+#            exit 1
+#          fi
+#
+#          regctl image copy ${{ env.GCP_IMAGE_PATH }}:${{ steps.vars.outputs.tag }} ${{ env.GCP_IMAGE_PATH }}:latest${{ matrix.image.tag }}
+#          regctl image copy ${{ env.GITHUB_IMAGE_PATH }}:${{ steps.vars.outputs.tag }} ${{ env.GITHUB_IMAGE_PATH }}:latest${{ matrix.image.tag }}
+#
+#      - name: Retag to LTS
+#        if: startsWith(github.ref, 'refs/tags/v') && (inputs.dry-run == false || inputs.dry-run == 'false') && (inputs.retag-lts == true || inputs.retag-lts == 'true')
+#        run: |
+#          echo "TODO remove this safety net after debugging inputs.retag-lts, its value: ${{ inputs.retag-lts }}"
+#          TAG=${GITHUB_REF#refs/*/}
+#          if [[ ! $TAG =~ ^v1\.0\.[0-9]+$ ]]; then
+#            echo "error there is a bug, tag is probably not the expected one: $TAG"
+#            exit 1
+#          fi
+#
+#          regctl image copy ${{ env.GCP_IMAGE_PATH }}:${{ steps.vars.outputs.tag }} ${{ env.GCP_IMAGE_PATH }}:latest-lts${{ matrix.image.tag }}
+#          regctl image copy ${{ env.GITHUB_IMAGE_PATH }}:${{ steps.vars.outputs.tag }} ${{ env.GITHUB_IMAGE_PATH }}:latest-lts${{ matrix.image.tag }}
